// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLZn-dYIaKFHv5cDv04VaaC3d3gOvfCA',
    appId: '1:542039405043:web:ff9bb4a83c2fb5a9966286',
    messagingSenderId: '542039405043',
    projectId: 'logistics-bb125',
    authDomain: 'logistics-bb125.firebaseapp.com',
    storageBucket: 'logistics-bb125.appspot.com',
    measurementId: 'G-HN3NM8HEP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG3uV7b3N7nurd1uEbtwsqAnOJ6G0fmXY',
    appId: '1:542039405043:android:374c00f675181829966286',
    messagingSenderId: '542039405043',
    projectId: 'logistics-bb125',
    storageBucket: 'logistics-bb125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVB_wev2PLRzuSe6efaNxnWbyYLyivMXA',
    appId: '1:542039405043:ios:3a98b0c193857778966286',
    messagingSenderId: '542039405043',
    projectId: 'logistics-bb125',
    storageBucket: 'logistics-bb125.appspot.com',
    iosBundleId: 'com.example.fExam',
  );
}
