// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOiomaydK9_VCJVNU-Q9HbahaMD337SIo',
    appId: '1:749782468223:web:b1dd8972c4b301a47e614a',
    messagingSenderId: '749782468223',
    projectId: 'u-exam',
    authDomain: 'u-exam.firebaseapp.com',
    databaseURL: 'https://u-exam-default-rtdb.firebaseio.com',
    storageBucket: 'u-exam.appspot.com',
    measurementId: 'G-30Y21QHHLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBklg1DQgPCO7clHBkNy9bRoU7e622f0',
    appId: '1:749782468223:android:d2ebfc60e6db07077e614a',
    messagingSenderId: '749782468223',
    projectId: 'u-exam',
    storageBucket: 'u-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc70LzRCRDqyTfSe96lix2wusvQ7__ZFU',
    appId: '1:749782468223:ios:7753934c016722357e614a',
    messagingSenderId: '749782468223',
    projectId: 'u-exam',
    storageBucket: 'u-exam.appspot.com',
    iosClientId: '749782468223-rt13a6o08ea6gkn7t2g3j531shunq459.apps.googleusercontent.com',
    iosBundleId: 'com.example.uExam',
  );
}
